//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syracuse.Mobitheque.Core {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syracuse.Mobitheque.Core.ApplicationResource", typeof(ApplicationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is on hold.
        /// </summary>
        public static string AccountInfoCountAvailableBooking {
            get {
                return ResourceManager.GetString("AccountInfoCountAvailableBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} are on hold.
        /// </summary>
        public static string AccountInfoCountAvailableBookings {
            get {
                return ResourceManager.GetString("AccountInfoCountAvailableBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is late.
        /// </summary>
        public static string AccountInfoCountLateLoan {
            get {
                return ResourceManager.GetString("AccountInfoCountLateLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} are late.
        /// </summary>
        public static string AccountInfoCountLateLoans {
            get {
                return ResourceManager.GetString("AccountInfoCountLateLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No booking available at the moment.
        /// </summary>
        public static string AccountInfoCountNotAvailableBookings {
            get {
                return ResourceManager.GetString("AccountInfoCountNotAvailableBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You borrowed {0} document.
        /// </summary>
        public static string AccountInfoCountOfBooking {
            get {
                return ResourceManager.GetString("AccountInfoCountOfBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have reserved {0} documents.
        /// </summary>
        public static string AccountInfoCountOfBookings {
            get {
                return ResourceManager.GetString("AccountInfoCountOfBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have reserved {0} document.
        /// </summary>
        public static string AccountInfoCountOfLoan {
            get {
                return ResourceManager.GetString("AccountInfoCountOfLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You borrowed {0} documents.
        /// </summary>
        public static string AccountInfoCountOfLoans {
            get {
                return ResourceManager.GetString("AccountInfoCountOfLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is to be returned on {1}.
        /// </summary>
        public static string AccountInfoReturnDateLoan {
            get {
                return ResourceManager.GetString("AccountInfoReturnDateLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} are to be returned on {1}.
        /// </summary>
        public static string AccountInfoReturnDateLoans {
            get {
                return ResourceManager.GetString("AccountInfoReturnDateLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are logged in as {0}.
        /// </summary>
        public static string AccountSwitchSuccess {
            get {
                return ResourceManager.GetString("AccountSwitchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Book.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Would you like to cancel the following booking :
        ///{0}
        ///Cancellation is final..
        /// </summary>
        public static string BookingCancelChoice {
            get {
                return ResourceManager.GetString("BookingCancelChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Booked on {0}.
        /// </summary>
        public static string BookingResultBookingDate {
            get {
                return ResourceManager.GetString("BookingResultBookingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My bookings.
        /// </summary>
        public static string Bookings {
            get {
                return ResourceManager.GetString("Bookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        public static string ButtonValidation {
            get {
                return ResourceManager.GetString("ButtonValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à From {0} to {1} .
        /// </summary>
        public static string DateToDate {
            get {
                return ResourceManager.GetString("DateToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à From {0} to {1} from {2} to {3}.
        /// </summary>
        public static string DateToDateHours {
            get {
                return ResourceManager.GetString("DateToDateHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} from {1}  to {2}.
        /// </summary>
        public static string DateToDateShort {
            get {
                return ResourceManager.GetString("DateToDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You will be temporarily logged out of your current session. Once the new account has been added, you can switch from one to the other in one click..
        /// </summary>
        public static string DisconectAuthorization {
            get {
                return ResourceManager.GetString("DisconectAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not available.
        /// </summary>
        public static string DisponibilityNo {
            get {
                return ResourceManager.GetString("DisponibilityNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Available.
        /// </summary>
        public static string DisponibilityYes {
            get {
                return ResourceManager.GetString("DisponibilityYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Downloads.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error has occurred.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your reservation request has failed.
        /// </summary>
        public static string FailBookingRequest {
            get {
                return ResourceManager.GetString("FailBookingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Renewal Impossible.
        /// </summary>
        public static string FailExtendLoan {
            get {
                return ResourceManager.GetString("FailExtendLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Did you forget this account on the application? You can always log back in to it later..
        /// </summary>
        public static string ForgetAccount {
            get {
                return ResourceManager.GetString("ForgetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous confirmer votre reservation à {0}.
        /// </summary>
        public static string HoldingChoice {
            get {
                return ResourceManager.GetString("HoldingChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Available to {0}.
        /// </summary>
        public static string HoldingDisponibilityText {
            get {
                return ResourceManager.GetString("HoldingDisponibilityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expected return on {0} at {1}.
        /// </summary>
        public static string HoldingDisponibilityTextDateBack {
            get {
                return ResourceManager.GetString("HoldingDisponibilityTextDateBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My establishment.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My loans.
        /// </summary>
        public static string Loans {
            get {
                return ResourceManager.GetString("Loans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Return on .
        /// </summary>
        public static string LoansDateBefore {
            get {
                return ResourceManager.GetString("LoansDateBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Late since the .
        /// </summary>
        public static string LoansDateLate {
            get {
                return ResourceManager.GetString("LoansDateLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please fill in this field.
        /// </summary>
        public static string MissingField {
            get {
                return ResourceManager.GetString("MissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This feature requires a network connection, please check this before trying again..
        /// </summary>
        public static string NetworkDisable {
            get {
                return ResourceManager.GetString("NetworkDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All my accounts.
        ///   Looks up a localized string similar to View online.
        /// </summary>
        public static string OnlineConsult {
            get {
                return ResourceManager.GetString("OnlineConsult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All my accounts.
        /// </summary>
        public static string OtherAccount {
            get {
                return ResourceManager.GetString("OtherAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pinned documents.
        /// </summary>
        public static string PinnedDocuments {
            get {
                return ResourceManager.GetString("PinnedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à News of the day.
        /// </summary>
        public static string PressDaily {
            get {
                return ResourceManager.GetString("PressDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à International News.
        /// </summary>
        public static string PressInternational {
            get {
                return ResourceManager.GetString("PressInternational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Would you like to extend this copy?
        ///{0}.
        /// </summary>
        public static string RenewChoice {
            get {
                return ResourceManager.GetString("RenewChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scanning a book.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} results.
        /// </summary>
        public static string SearchViewResultCount {
            get {
                return ResourceManager.GetString("SearchViewResultCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} result.
        /// </summary>
        public static string SearchViewResultNull {
            get {
                return ResourceManager.GetString("SearchViewResultNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A to Z (Author).
        /// </summary>
        public static string SortOptionAutorASC {
            get {
                return ResourceManager.GetString("SortOptionAutorASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Z to A (Author).
        /// </summary>
        public static string SortOptionAutorDESC {
            get {
                return ResourceManager.GetString("SortOptionAutorDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pertinence.
        /// </summary>
        public static string SortOptionPertinence {
            get {
                return ResourceManager.GetString("SortOptionPertinence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à most recent.
        /// </summary>
        public static string SortOptionTimeASC {
            get {
                return ResourceManager.GetString("SortOptionTimeASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à less recent.
        /// </summary>
        public static string SortOptionTimeDESC {
            get {
                return ResourceManager.GetString("SortOptionTimeDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A to Z (Title).
        /// </summary>
        public static string SortOptionTitleASC {
            get {
                return ResourceManager.GetString("SortOptionTitleASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Z to A (Title).
        /// </summary>
        public static string SortOptionTitleDESC {
            get {
                return ResourceManager.GetString("SortOptionTitleDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The document will be made available to you shortly..
        /// </summary>
        public static string SuccessBookingRequest {
            get {
                return ResourceManager.GetString("SuccessBookingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your booking has been cancelled for the title {0}.
        /// </summary>
        public static string SuccessCancelBooking {
            get {
                return ResourceManager.GetString("SuccessCancelBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your bookings has been extended for the title {0}.
        /// </summary>
        public static string SuccessExtendLoan {
            get {
                return ResourceManager.GetString("SuccessExtendLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
