//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syracuse.Mobitheque.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syracuse.Mobitheque.Core.ApplicationResource", typeof(ApplicationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is on hold.
        /// </summary>
        public static string AccountInfoCountAvailableBooking {
            get {
                return ResourceManager.GetString("AccountInfoCountAvailableBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} are on hold.
        /// </summary>
        public static string AccountInfoCountAvailableBookings {
            get {
                return ResourceManager.GetString("AccountInfoCountAvailableBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is late.
        /// </summary>
        public static string AccountInfoCountLateLoan {
            get {
                return ResourceManager.GetString("AccountInfoCountLateLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} are late.
        /// </summary>
        public static string AccountInfoCountLateLoans {
            get {
                return ResourceManager.GetString("AccountInfoCountLateLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reserved {0} documents.
        /// </summary>
        public static string AccountInfoCountOfBookings {
            get {
                return ResourceManager.GetString("AccountInfoCountOfBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You borrowed {0} documents.
        /// </summary>
        public static string AccountInfoCountOfLoans {
            get {
                return ResourceManager.GetString("AccountInfoCountOfLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is to be returned on {1}.
        /// </summary>
        public static string AccountInfoReturnDateLoan {
            get {
                return ResourceManager.GetString("AccountInfoReturnDateLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} are to be returned on {1}.
        /// </summary>
        public static string AccountInfoReturnDateLoans {
            get {
                return ResourceManager.GetString("AccountInfoReturnDateLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My bookings.
        /// </summary>
        public static string Bookings {
            get {
                return ResourceManager.GetString("Bookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonValidation {
            get {
                return ResourceManager.GetString("ButtonValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a new account we will have to end the current session do you want to continue?.
        /// </summary>
        public static string DisconectAuthorization {
            get {
                return ResourceManager.GetString("DisconectAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reservation request has failed.
        /// </summary>
        public static string FailBookingRequest {
            get {
                return ResourceManager.GetString("FailBookingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Impossible.
        /// </summary>
        public static string FailExtendLoan {
            get {
                return ResourceManager.GetString("FailExtendLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My loans.
        /// </summary>
        public static string Loans {
            get {
                return ResourceManager.GetString("Loans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in this field.
        /// </summary>
        public static string MissingField {
            get {
                return ResourceManager.GetString("MissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All my accounts.
        /// </summary>
        public static string OtherAccount {
            get {
                return ResourceManager.GetString("OtherAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} results.
        /// </summary>
        public static string SearchViewResultCount {
            get {
                return ResourceManager.GetString("SearchViewResultCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 result.
        /// </summary>
        public static string SearchViewResultNull {
            get {
                return ResourceManager.GetString("SearchViewResultNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A to Z (Author).
        /// </summary>
        public static string SortOptionAutorASC {
            get {
                return ResourceManager.GetString("SortOptionAutorASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z to A (Author).
        /// </summary>
        public static string SortOptionAutorDESC {
            get {
                return ResourceManager.GetString("SortOptionAutorDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to most recent.
        /// </summary>
        public static string SortOptionTimeASC {
            get {
                return ResourceManager.GetString("SortOptionTimeASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less recent.
        /// </summary>
        public static string SortOptionTimeDESC {
            get {
                return ResourceManager.GetString("SortOptionTimeDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A to Z (Title).
        /// </summary>
        public static string SortOptionTitleASC {
            get {
                return ResourceManager.GetString("SortOptionTitleASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z to A (Title).
        /// </summary>
        public static string SortOptionTitleDESC {
            get {
                return ResourceManager.GetString("SortOptionTitleDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reservation request was successful.
        /// </summary>
        public static string SuccessBookingRequest {
            get {
                return ResourceManager.GetString("SuccessBookingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation was successful for the title {0}.
        /// </summary>
        public static string SuccessCancelBooking {
            get {
                return ResourceManager.GetString("SuccessCancelBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension has been made for the title {0}.
        /// </summary>
        public static string SuccessExtendLoan {
            get {
                return ResourceManager.GetString("SuccessExtendLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
