//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syracuse.Mobitheque.Core {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Syracuse.Mobitheque.Core.ApplicationResource", typeof(ApplicationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        public static string AccountInfoCountAvailableBooking {
            get {
                return ResourceManager.GetString("AccountInfoCountAvailableBooking", resourceCulture);
            }
        }
        
        public static string AccountInfoCountAvailableBookings {
            get {
                return ResourceManager.GetString("AccountInfoCountAvailableBookings", resourceCulture);
            }
        }
        
        public static string AccountInfoCountLateLoan {
            get {
                return ResourceManager.GetString("AccountInfoCountLateLoan", resourceCulture);
            }
        }
        
        public static string AccountInfoCountLateLoans {
            get {
                return ResourceManager.GetString("AccountInfoCountLateLoans", resourceCulture);
            }
        }
        
        public static string AccountInfoCountNotAvailableBookings {
            get {
                return ResourceManager.GetString("AccountInfoCountNotAvailableBookings", resourceCulture);
            }
        }
        
        public static string AccountInfoCountOfBooking {
            get {
                return ResourceManager.GetString("AccountInfoCountOfBooking", resourceCulture);
            }
        }
        
        public static string AccountInfoCountOfBookings {
            get {
                return ResourceManager.GetString("AccountInfoCountOfBookings", resourceCulture);
            }
        }
        
        public static string AccountInfoCountOfLoan {
            get {
                return ResourceManager.GetString("AccountInfoCountOfLoan", resourceCulture);
            }
        }
        
        public static string AccountInfoCountOfLoans {
            get {
                return ResourceManager.GetString("AccountInfoCountOfLoans", resourceCulture);
            }
        }
        
        public static string AccountInfoReturnDateLoan {
            get {
                return ResourceManager.GetString("AccountInfoReturnDateLoan", resourceCulture);
            }
        }
        
        public static string AccountInfoReturnDateLoans {
            get {
                return ResourceManager.GetString("AccountInfoReturnDateLoans", resourceCulture);
            }
        }
        
        public static string AccountSwitchSuccess {
            get {
                return ResourceManager.GetString("AccountSwitchSuccess", resourceCulture);
            }
        }
        
        public static string BookingCancelChoice {
            get {
                return ResourceManager.GetString("BookingCancelChoice", resourceCulture);
            }
        }
        
        public static string BookingResultBookingDate {
            get {
                return ResourceManager.GetString("BookingResultBookingDate", resourceCulture);
            }
        }
        
        public static string Bookings {
            get {
                return ResourceManager.GetString("Bookings", resourceCulture);
            }
        }
        
        public static string ButtonValidation {
            get {
                return ResourceManager.GetString("ButtonValidation", resourceCulture);
            }
        }
        
        public static string DateToDate {
            get {
                return ResourceManager.GetString("DateToDate", resourceCulture);
            }
        }
        
        public static string DateToDateShort {
            get {
                return ResourceManager.GetString("DateToDateShort", resourceCulture);
            }
        }
        
        public static string DisconectAuthorization {
            get {
                return ResourceManager.GetString("DisconectAuthorization", resourceCulture);
            }
        }
        
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        public static string FailBookingRequest {
            get {
                return ResourceManager.GetString("FailBookingRequest", resourceCulture);
            }
        }
        
        public static string FailExtendLoan {
            get {
                return ResourceManager.GetString("FailExtendLoan", resourceCulture);
            }
        }
        
        public static string HoldingChoice {
            get {
                return ResourceManager.GetString("HoldingChoice", resourceCulture);
            }
        }
        
        public static string HoldingDisponibilityText {
            get {
                return ResourceManager.GetString("HoldingDisponibilityText", resourceCulture);
            }
        }
        
        public static string HoldingDisponibilityTextDateBack {
            get {
                return ResourceManager.GetString("HoldingDisponibilityTextDateBack", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        public static string Loans {
            get {
                return ResourceManager.GetString("Loans", resourceCulture);
            }
        }
        
        public static string MissingField {
            get {
                return ResourceManager.GetString("MissingField", resourceCulture);
            }
        }
        
        public static string NetworkDisable {
            get {
                return ResourceManager.GetString("NetworkDisable", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string OtherAccount {
            get {
                return ResourceManager.GetString("OtherAccount", resourceCulture);
            }
        }
        
        public static string PinnedDocuments {
            get {
                return ResourceManager.GetString("PinnedDocuments", resourceCulture);
            }
        }
        
        public static string RenewChoice {
            get {
                return ResourceManager.GetString("RenewChoice", resourceCulture);
            }
        }
        
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        public static string SearchViewResultCount {
            get {
                return ResourceManager.GetString("SearchViewResultCount", resourceCulture);
            }
        }
        
        public static string SearchViewResultNull {
            get {
                return ResourceManager.GetString("SearchViewResultNull", resourceCulture);
            }
        }
        
        public static string SortOptionAutorASC {
            get {
                return ResourceManager.GetString("SortOptionAutorASC", resourceCulture);
            }
        }
        
        public static string SortOptionAutorDESC {
            get {
                return ResourceManager.GetString("SortOptionAutorDESC", resourceCulture);
            }
        }
        
        public static string SortOptionPertinence {
            get {
                return ResourceManager.GetString("SortOptionPertinence", resourceCulture);
            }
        }
        
        public static string SortOptionTimeASC {
            get {
                return ResourceManager.GetString("SortOptionTimeASC", resourceCulture);
            }
        }
        
        public static string SortOptionTimeDESC {
            get {
                return ResourceManager.GetString("SortOptionTimeDESC", resourceCulture);
            }
        }
        
        public static string SortOptionTitleASC {
            get {
                return ResourceManager.GetString("SortOptionTitleASC", resourceCulture);
            }
        }
        
        public static string SortOptionTitleDESC {
            get {
                return ResourceManager.GetString("SortOptionTitleDESC", resourceCulture);
            }
        }
        
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        public static string SuccessBookingRequest {
            get {
                return ResourceManager.GetString("SuccessBookingRequest", resourceCulture);
            }
        }
        
        public static string SuccessCancelBooking {
            get {
                return ResourceManager.GetString("SuccessCancelBooking", resourceCulture);
            }
        }
        
        public static string SuccessExtendLoan {
            get {
                return ResourceManager.GetString("SuccessExtendLoan", resourceCulture);
            }
        }
        
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
