//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syracuse.Mobitheque.UI {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource_fr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource_fr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Syracuse.Mobitheque.UI.AppResource.fr", typeof(AppResource_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        public static string AccountTitle {
            get {
                return ResourceManager.GetString("AccountTitle", resourceCulture);
            }
        }
        public static string Available
        {
            get
            {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }

        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        public static string Copies {
            get {
                return ResourceManager.GetString("Copies", resourceCulture);
            }
        }
        public static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        public static string DepartmentTitle {
            get {
                return ResourceManager.GetString("DepartmentTitle", resourceCulture);
            }
        }

        public static string ErrorLibraryWebSite
        {
            get
            {
                return ResourceManager.GetString("ErrorLibraryWebSite", resourceCulture);
            }
        }

        public static string Extend {
            get {
                return ResourceManager.GetString("Extend", resourceCulture);
            }
        }
        
        public static string FilterOption {
            get {
                return ResourceManager.GetString("FilterOption", resourceCulture);
            }
        }
        
        public static string LibraryTitle {
            get {
                return ResourceManager.GetString("LibraryTitle", resourceCulture);
            }
        }
        
        public static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        public static string NetworkError
        {
            get
            {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }

        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }

         public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string SortOption {
            get {
                return ResourceManager.GetString("SortOption", resourceCulture);
            }
        }
        
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        public static string Synthesis {
            get {
                return ResourceManager.GetString("Synthesis", resourceCulture);
            }
        }
        public static string Validate
        {
            get
            {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
    }
}
